title = "Mark Groves"
theme = "hello-friend-ng"
baseUrl = "https://markgroves.us"
languageCode = "en-us"
enableGitInfo = true

[author]
name = 'Mark Groves'
[permalinks]
  posts = "/:year/:month/:day/:title/"
  links = "/:year/:month/:day/:title/"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  gitUrl = "https://github.com/markgrovs/markgroves.us/commit/"
  webmentionTestUrl = true
  webmentions = true
  # Metadata mostly used in document's head
  description = "Homepage and blog by Mark Groves"
  keywords = "homepage, blog"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
    # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/markgrovs"

  [[params.social]]
    name = "email"
    url  = "mailto:mark@markgroves.us"

  [[params.social]]
    name = "github"
    url  = "https://github.com/markgrovs"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/mark-groves/"
  [[params.social]]
    name = "mastodon"
    url = "https://mastodon.host/@markgroves"
  


[languages]
  [languages.en]
    title = "Mark Groves"
    subtitle = "homepage and blog"
    homeSubtitle = "software professional, but mostly still figuring it out."
    keywords = ""
    copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "/home/markgroves"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "archive"
    name       = "archive"
    url        = "posts/" 
#  [[menu.main]]
#    identifier = "about"
#    name       = "about"
#    url        = "about/"


